name = "Oracle"
uuid = "3328109a-0d39-11e9-3813-abcec9a1b4fe"
license = "MIT"
authors = ["Felipe Noronha <felipenoris@gmail.com>"]
version = "0.0.1"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
